# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Session-Driver-memcached_mysql
version:      0.01
version_from: lib/CGI/Session/Driver/memcached_mysql.pm
installdirs:  site
requires:
    Cache::Memcached:              
    CGI::Session:                  4
    Test::More:                    

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
